# Generated by Django 5.0 on 2023-12-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimagesmodel',
            options={'verbose_name': 'Изображения для карусели', 'verbose_name_plural': 'Изображение для карусели'},
        ),
    ]
