# Generated by Django 5.0 on 2023-12-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0002_alter_carouselimagesmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotmodel',
            name='video_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
