version: "3"

services:
  web-app:
    build:
      context: .
    container_name: frontier_app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=frontier
      - DB_USER=frontier_user
      - DB_PASSWORD=qwerty2F
    volumes:
      - ./frontier:/frontier
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: frontier
      POSTGRES_USER: frontier_user
      POSTGRES_PASSWORD: qwerty2F

    volumes:
      - D:\postgres_data\frontier_db:/var/lib/postgresql/data

  redis:
    image: redis
    hostname: redis
    restart: always

  worker:
    build:
      context: .
    hostname: worker
    ports:
      - 587:587
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=frontier
      - DB_USER=frontier_user
      - DB_PASSWORD=qwerty2F
    command: celery -A Frontier worker --loglevel=info
    volumes:
      - ./frontier:/frontier
    links:
      - redis
    depends_on:
      - web-app
      - redis

#  nginx:
#    build: ./nginx
#    volumes:
#      - ./frontier/static:/static
#      - ./frontier/media:/media
#    ports:
#      - 80:80
#    depends_on:
#      - web-app





