# Generated by Django 5.0 on 2023-12-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('descr', models.TextField(verbose_name='Описание класса')),
            ],
            options={
                'verbose_name': 'Класс оружия',
                'verbose_name_plural': 'Классы оружия',
            },
        ),
        migrations.CreateModel(
            name='WeaponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название оружия')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('video_link', models.CharField(verbose_name='Ссылка на видео')),
                ('descr', models.TextField(verbose_name='Описание оружия')),
                ('weapon_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='weapons.weaponclassmodel', verbose_name='Класс оружия')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружия',
            },
        ),
    ]
