# Generated by Django 5.0 on 2023-12-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponmodel',
            name='video_link',
            field=models.CharField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
