# Generated by Django 5.0 on 2023-12-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationmodel',
            options={'verbose_name': 'Записи подтверждения E-mail', 'verbose_name_plural': 'Запись подтверждения E-mail'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили', 'verbose_name_plural': 'Профиль'},
        ),
    ]
