# Generated by Django 4.2.7 on 2023-11-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monarchcorestagemodel',
            old_name='stage',
            new_name='name',
        ),
    ]
