# Generated by Django 4.2.7 on 2023-11-06 12:55

from django.db import migrations, models
import django.db.models.deletion
import titans.models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractEquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('equipment_name', models.CharField(max_length=255)),
                ('descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('upper_text', models.TextField()),
                ('lower_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlockWithImageVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='additional/')),
                ('video_link', models.CharField(blank=True, max_length=255)),
                ('image_or_video_descr', models.CharField(max_length=255)),
                ('master_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='titans.chaptermodel')),
            ],
        ),
        migrations.CreateModel(
            name='FirstGenTitanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('titan_name', models.CharField(max_length=255)),
                ('mp_descr', models.TextField(blank=True)),
                ('mp_image', models.ImageField(upload_to=titans.models.AbstractTitanModel.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SecondGenTitanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('titan_name', models.CharField(max_length=255)),
                ('mp_descr', models.TextField(blank=True)),
                ('mp_image', models.ImageField(upload_to=titans.models.AbstractTitanModel.user_directory_path)),
                ('full_descr', models.TextField(blank=True)),
                ('video_link', models.CharField(max_length=255)),
                ('ancestor_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='titans.firstgentitanmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TitanKitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('titan_name', models.CharField(max_length=255)),
                ('mp_descr', models.TextField(blank=True)),
                ('mp_image', models.ImageField(upload_to=titans.models.AbstractTitanModel.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
        migrations.CreateModel(
            name='TitanWeaponModel',
            fields=[
                ('abstractequipmentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='titans.abstractequipmentmodel')),
                ('weapon_image', models.ImageField(upload_to=titans.models.TitanWeaponModel.user_directory_path)),
            ],
            bases=('titans.abstractequipmentmodel',),
        ),
        migrations.AddField(
            model_name='firstgentitanmodel',
            name='master_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_titans', to='titans.mainpagemodel'),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='master_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='titans.mainpagemodel'),
        ),
        migrations.AddField(
            model_name='abstractequipmentmodel',
            name='master_titan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='titans.secondgentitanmodel'),
        ),
    ]
