# Generated by Django 4.2.7 on 2023-11-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0002_abstractequipmentmodel_chaptermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagemodel',
            name='page_name',
            field=models.CharField(default='TITAN', max_length=255),
        ),
    ]
