# Generated by Django 4.2.7 on 2023-11-07 11:02

from django.db import migrations, models
import django.db.models.deletion
import titans.models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0003_mainpagemodel_page_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptermodel',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='contentblockwithimagevideomodel',
            options={'verbose_name': 'Основная контентная единица', 'verbose_name_plural': 'Основные контентные единицы'},
        ),
        migrations.AlterModelOptions(
            name='firstgentitanmodel',
            options={'verbose_name': 'Титан первого поколения', 'verbose_name_plural': 'Титаны первого поколения'},
        ),
        migrations.AlterModelOptions(
            name='mainpagemodel',
            options={'verbose_name': 'Основная страница', 'verbose_name_plural': 'Основные страницы'},
        ),
        migrations.AlterModelOptions(
            name='secondgentitanmodel',
            options={'verbose_name': 'Титан второго поколения', 'verbose_name_plural': 'Титаны второго поколения'},
        ),
        migrations.AlterModelOptions(
            name='titankitmodel',
            options={'verbose_name': 'Дополнительный набор титана', 'verbose_name_plural': 'Дополнительные наборы титанов'},
        ),
        migrations.AlterModelOptions(
            name='titanweaponmodel',
            options={'verbose_name': 'Основное снаряжение титанов', 'verbose_name_plural': 'Основное снаряжение титанов'},
        ),
        migrations.RemoveField(
            model_name='abstractequipmentmodel',
            name='equipment_name',
        ),
        migrations.RemoveField(
            model_name='chaptermodel',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='contentblockwithimagevideomodel',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='firstgentitanmodel',
            name='titan_name',
        ),
        migrations.RemoveField(
            model_name='mainpagemodel',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='secondgentitanmodel',
            name='titan_name',
        ),
        migrations.RemoveField(
            model_name='titankitmodel',
            name='titan_name',
        ),
        migrations.AddField(
            model_name='abstractequipmentmodel',
            name='name',
            field=models.CharField(default='Empty', max_length=255, verbose_name='Название снаряжения'),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='name',
            field=models.CharField(default='Empty', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contentblockwithimagevideomodel',
            name='name',
            field=models.CharField(default='Empty', max_length=255, verbose_name='Имя блока'),
        ),
        migrations.AddField(
            model_name='firstgentitanmodel',
            name='name',
            field=models.CharField(default='Empty', max_length=255, verbose_name='Имя титана'),
        ),
        migrations.AddField(
            model_name='mainpagemodel',
            name='name',
            field=models.CharField(default='Empty', max_length=255, verbose_name='Имя страницы'),
        ),
        migrations.AddField(
            model_name='secondgentitanmodel',
            name='name',
            field=models.CharField(default='Empty', max_length=255, verbose_name='Имя титана'),
        ),
        migrations.AddField(
            model_name='titankitmodel',
            name='name',
            field=models.CharField(default='Empty', max_length=255, verbose_name='Имя титана'),
        ),
        migrations.AlterField(
            model_name='abstractequipmentmodel',
            name='descr',
            field=models.TextField(verbose_name='Описание снаряжения'),
        ),
        migrations.AlterField(
            model_name='abstractequipmentmodel',
            name='master_titan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='titans.secondgentitanmodel', verbose_name='Титан-владелец'),
        ),
        migrations.AlterField(
            model_name='abstractequipmentmodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='lower_text',
            field=models.TextField(verbose_name='Концовка главы'),
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='master_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='titans.mainpagemodel', verbose_name='Главная страница'),
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='upper_text',
            field=models.TextField(verbose_name='Вступительный текст'),
        ),
        migrations.AlterField(
            model_name='contentblockwithimagevideomodel',
            name='content',
            field=models.TextField(verbose_name='Наполнение'),
        ),
        migrations.AlterField(
            model_name='contentblockwithimagevideomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='additional/', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='contentblockwithimagevideomodel',
            name='image_or_video_descr',
            field=models.CharField(max_length=255, verbose_name='Описание фото/видео'),
        ),
        migrations.AlterField(
            model_name='contentblockwithimagevideomodel',
            name='master_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='titans.chaptermodel', verbose_name='Связанная глава'),
        ),
        migrations.AlterField(
            model_name='contentblockwithimagevideomodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='contentblockwithimagevideomodel',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='firstgentitanmodel',
            name='master_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_titans', to='titans.mainpagemodel', verbose_name='Главная страница'),
        ),
        migrations.AlterField(
            model_name='firstgentitanmodel',
            name='mp_descr',
            field=models.TextField(blank=True, verbose_name='Описание на основной странице'),
        ),
        migrations.AlterField(
            model_name='firstgentitanmodel',
            name='mp_image',
            field=models.ImageField(upload_to=titans.models.AbstractTitanModel.user_directory_path, verbose_name='Фото на основной странице'),
        ),
        migrations.AlterField(
            model_name='firstgentitanmodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='secondgentitanmodel',
            name='ancestor_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='titans.firstgentitanmodel', verbose_name='Модель-предок'),
        ),
        migrations.AlterField(
            model_name='secondgentitanmodel',
            name='full_descr',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='secondgentitanmodel',
            name='mp_descr',
            field=models.TextField(blank=True, verbose_name='Описание на основной странице'),
        ),
        migrations.AlterField(
            model_name='secondgentitanmodel',
            name='mp_image',
            field=models.ImageField(upload_to=titans.models.AbstractTitanModel.user_directory_path, verbose_name='Фото на основной странице'),
        ),
        migrations.AlterField(
            model_name='secondgentitanmodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='secondgentitanmodel',
            name='video_link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='titankitmodel',
            name='mp_descr',
            field=models.TextField(blank=True, verbose_name='Описание на основной странице'),
        ),
        migrations.AlterField(
            model_name='titankitmodel',
            name='mp_image',
            field=models.ImageField(upload_to=titans.models.AbstractTitanModel.user_directory_path, verbose_name='Фото на основной странице'),
        ),
        migrations.AlterField(
            model_name='titankitmodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='titanweaponmodel',
            name='weapon_image',
            field=models.ImageField(upload_to=titans.models.TitanWeaponModel.user_directory_path, verbose_name='Изображение оружия'),
        ),
    ]
