# Generated by Django 4.2.7 on 2023-11-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0005_remove_titankitmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titanweaponmodel',
            name='weapon_type',
            field=models.CharField(choices=[('MW', 'Основное оружие'), ('SW', 'Дополнительное оружие'), ('TW', 'Тактическое оружие'), ('CW', 'Ядро')], default='MW', max_length=2),
        ),
    ]
