# Generated by Django 4.2.7 on 2023-11-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0006_titanweaponmodel_weapon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondgentitanmodel',
            name='strategy',
            field=models.TextField(blank=True, verbose_name='Стратегия'),
        ),
        migrations.AlterField(
            model_name='titanweaponmodel',
            name='weapon_type',
            field=models.CharField(choices=[('MW', 'Основное оружие'), ('SW', 'Дополнительное оружие'), ('TW', 'Тактическое оружие'), ('DW', 'Оборонительное оружие'), ('CW', 'Ядро')], default='MW', max_length=2),
        ),
    ]
