# Generated by Django 4.2.7 on 2023-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0007_secondgentitanmodel_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondgentitanmodel',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Слот для монарха'),
        ),
        migrations.AlterField(
            model_name='titanweaponmodel',
            name='weapon_type',
            field=models.CharField(choices=[('MW', 'Основное оружие'), ('SW', 'Дополнительное оружие'), ('TW', 'Тактическое оружие'), ('DW', 'Оборонительное оружие'), ('CW', 'Ядро')], default='MW', max_length=2, verbose_name='Тип оружия'),
        ),
    ]
