# Generated by Django 4.2.7 on 2023-11-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0008_secondgentitanmodel_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractequipmentmodel',
            name='master_titan',
        ),
        migrations.AddField(
            model_name='titankitmodel',
            name='master_titan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits', to='titans.secondgentitanmodel', verbose_name='Титан-владелец'),
        ),
        migrations.AddField(
            model_name='titanweaponmodel',
            name='master_titan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon', to='titans.secondgentitanmodel', verbose_name='Титан-владелец'),
        ),
        migrations.AlterField(
            model_name='firstgentitanmodel',
            name='master_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_titan', to='titans.mainpagemodel', verbose_name='Главная страница'),
        ),
    ]
