# Generated by Django 4.2.7 on 2023-11-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0009_remove_abstractequipmentmodel_master_titan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptermodel',
            name='master_page',
        ),
        migrations.RemoveField(
            model_name='firstgentitanmodel',
            name='master_page',
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='curr_page',
            field=models.CharField(choices=[('TP', 'Главная странница титанов'), ('PP', 'Главная странница пилотов'), ('UN', 'Неопределено')], default='UN', max_length=2, verbose_name='Относится к страннице:'),
        ),
        migrations.DeleteModel(
            name='MainPageModel',
        ),
    ]
