# Generated by Django 4.2.7 on 2023-11-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0010_remove_chaptermodel_master_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentblockwithimagevideomodel',
            old_name='image_or_video_descr',
            new_name='media_descr',
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='curr_page',
            field=models.CharField(choices=[('TP', 'Главная страница титанов'), ('PP', 'Главная страница пилотов'), ('UN', 'Неопределено')], default='UN', max_length=2, verbose_name='Относится к странице:'),
        ),
    ]
