# Generated by Django 4.2.7 on 2023-11-13 13:34

import Frontier.common.models
from django.db import migrations, models
import django.db.models.deletion
import titans.models


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0011_rename_image_or_video_descr_contentblockwithimagevideomodel_media_descr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Empty', max_length=255, verbose_name='Имя блока')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Наполнение')),
                ('image', models.ImageField(blank=True, null=True, upload_to=titans.models.AbstractContentModel.user_directory_path, verbose_name='Ссылка на изображение')),
            ],
            bases=(Frontier.common.models.NormalStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonarchCoreStageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='Empty', max_length=255, verbose_name='Стадия эволюции')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('descr', models.TextField(verbose_name='Описание стадии')),
            ],
            options={
                'verbose_name': 'Стадия эволюции Монарха',
                'verbose_name_plural': 'Стадии эволюции Монарха',
            },
            bases=(Frontier.common.models.NormalStringMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='secondgentitanmodel',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='titankitmodel',
            name='master_titan',
        ),
        migrations.RemoveField(
            model_name='titanweaponmodel',
            name='master_titan',
        ),
        migrations.AddField(
            model_name='titankitmodel',
            name='titan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits', to='titans.secondgentitanmodel', verbose_name='Титан-владелец'),
        ),
        migrations.AddField(
            model_name='titanweaponmodel',
            name='titan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon', to='titans.secondgentitanmodel', verbose_name='Титан-владелец'),
        ),
        migrations.AlterField(
            model_name='secondgentitanmodel',
            name='ancestor_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='titans.firstgentitanmodel', verbose_name='Модель-предок'),
        ),
        migrations.CreateModel(
            name='MediaContentBlockModel',
            fields=[
                ('abstractcontentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='titans.abstractcontentmodel')),
                ('video_link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на видео')),
                ('media_descr', models.CharField(max_length=255, verbose_name='Описание фото/видео')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='titans.chaptermodel', verbose_name='Связанная глава')),
            ],
            options={
                'verbose_name': 'Основная контентная единица',
                'verbose_name_plural': 'Основные контентные единицы',
            },
            bases=('titans.abstractcontentmodel',),
        ),
        migrations.CreateModel(
            name='MonarchCoreUpgradeModel',
            fields=[
                ('abstractcontentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='titans.abstractcontentmodel')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades', to='titans.monarchcorestagemodel', verbose_name='Связанная стадия')),
            ],
            options={
                'verbose_name': 'Улучшение ядра Монарха',
                'verbose_name_plural': 'Улучшения ядра Монарха',
            },
            bases=('titans.abstractcontentmodel',),
        ),
        migrations.CreateModel(
            name='StrategyBlock',
            fields=[
                ('abstractcontentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='titans.abstractcontentmodel')),
                ('titan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy', to='titans.firstgentitanmodel', verbose_name='Титан-владелец')),
            ],
            options={
                'verbose_name': 'Блок стратегии',
                'verbose_name_plural': 'Блоки стратегии',
            },
            bases=('titans.abstractcontentmodel',),
        ),
        migrations.DeleteModel(
            name='ContentBlockWithImageVideoModel',
        ),
    ]
