# Generated by Django 4.2.7 on 2023-11-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0012_abstractcontentmodel_monarchcorestagemodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StrategyBlock',
            new_name='StrategyBlockModel',
        ),
    ]
