# Generated by Django 4.2.7 on 2023-11-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titans', '0013_rename_strategyblock_strategyblockmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondgentitanmodel',
            name='strategy',
        ),
        migrations.AlterField(
            model_name='strategyblockmodel',
            name='titan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy', to='titans.secondgentitanmodel', verbose_name='Титан-владелец'),
        ),
    ]
